# Lab | Web Scraping

Welcome to the "Books to Scrape" Web Scraping Adventure Lab!

**Objective**

In this lab, we will embark on a mission to unearth valuable insights from the data available on Books to Scrape, an online platform showcasing a wide variety of books. As data analyst, you have been tasked with scraping a specific subset of book data from Books to Scrape to assist publishing companies in understanding the landscape of highly-rated books across different genres. Your insights will help shape future book marketing strategies and publishing decisions.

**Background**

In a world where data has become the new currency, businesses are leveraging big data to make informed decisions that drive success and profitability. The publishing industry, much like others, utilizes data analytics to understand market trends, reader preferences, and the performance of books based on factors such as genre, author, and ratings. Books to Scrape serves as a rich source of such data, offering detailed information about a diverse range of books, making it an ideal platform for extracting insights to aid in informed decision-making within the literary world.

**Task**

Your task is to create a Python script using BeautifulSoup and pandas to scrape Books to Scrape book data, focusing on book ratings and genres. The script should be able to filter books with ratings above a certain threshold and in specific genres. Additionally, the script should structure the scraped data in a tabular format using pandas for further analysis.

**Expected Outcome**

A function named `scrape_books` that takes two parameters: `min_rating` and `max_price`. The function should scrape book data from the "Books to Scrape" website and return a `pandas` DataFrame with the following columns:

**Expected Outcome**

- A function named `scrape_books` that takes two parameters: `min_rating` and `max_price`.
- The function should return a DataFrame with the following columns:
  - **UPC**: The Universal Product Code (UPC) of the book.
  - **Title**: The title of the book.
  - **Price (£)**: The price of the book in pounds.
  - **Rating**: The rating of the book (1-5 stars).
  - **Genre**: The genre of the book.
  - **Availability**: Whether the book is in stock or not.
  - **Description**: A brief description or product description of the book (if available).
  
You will execute this script to scrape data for books with a minimum rating of `4.0 and above` and a maximum price of `£20`. 

Remember to experiment with different ratings and prices to ensure your code is versatile and can handle various searches effectively!

**Resources**

- [Beautiful Soup Documentation](https://www.crummy.com/software/BeautifulSoup/bs4/doc/)
- [Pandas Documentation](https://pandas.pydata.org/pandas-docs/stable/index.html)
- [Books to Scrape](https://books.toscrape.com/)

**Hint**

Your first mission is to familiarize yourself with the **Books to Scrape** website. Navigate to [Books to Scrape](http://books.toscrape.com/) and explore the available books to understand their layout and structure. 

Next, think about how you can set parameters for your data extraction:

- **Minimum Rating**: Focus on books with a rating of 4.0 and above.
- **Maximum Price**: Filter for books priced up to £20.

After reviewing the site, you can construct a plan for scraping relevant data. Pay attention to the details displayed for each book, including the title, price, rating, and availability. This will help you identify the correct HTML elements to target with your scraping script.

Make sure to build your scraping URL and logic based on the patterns you observe in the HTML structure of the book listings!


---

**Best of luck! Immerse yourself in the world of books, and may the data be with you!**

**Important Note**:

In the fast-changing online world, websites often update and change their structures. When you try this lab, the **Books to Scrape** website might differ from what you expect.

If you encounter issues due to these changes, like new rules or obstacles preventing data extraction, don’t worry! Get creative.

You can choose another website that interests you and is suitable for scraping data. Options like Wikipedia, The New York Times, or even library databases are great alternatives. The main goal remains the same: extract useful data and enhance your web scraping skills while exploring a source of information you enjoy. This is your opportunity to practice and adapt to different web environments!

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re

url='https://books.toscrape.com/'
# Now we identify ourserlves as "humans", and not bots to avoid being blocked.
headers = {
  "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36"
}
response = requests.get(url, headers=headers)
print(response) # we check the response is correct =200
print(response.headers['Content-Type']) # we check our content is html
soup = BeautifulSoup(response.content, 'html.parser') #we store the html info in soup with a nice structure
type(soup)

<Response [200]>
text/html

bs4.BeautifulSoup

In [2]:
#Now is time to start finding the tags, attributes we need
#we look for the tags that includes inforation from the books displayed on the main pages
book_tags= soup.find_all('article',class_='product_pod')
len(book_tags)
print(book_tags[0])

<article class="product_pod">
<div class="image_container">
<a href="catalogue/a-light-in-the-attic_1000/index.html"><img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/></a>
</div>
<p class="star-rating Three">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">A Light in the ...</a></h3>
<div class="product_price">
<p class="price_color">£51.77</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>

In [3]:
#test if we get the names of the book here
name = book_tags[0].find('h3').find('a')['title']
print(name)

A Light in the Attic

In [4]:
#Now, we find the elements that contain name, price and rating from the main page, we target each element to find the price
price=float(book_tags[0].find('p', class_='price_color').getText().strip('£'))
price

51.77

In [5]:
#Now, we find the elements that make up our filter, finding the rating
rating_dic={'One':1, 'Two':2, 'Three':3, 'Four':4, 'Five':5}

rating_w=book_tags[0].find('p', class_='star-rating')['class'][1]
print(rating_w)
rating_n=rating_dic[rating_w]
rating_n

Three

3

In [7]:
#Now, we find the elements that make up our filter, finding the availability
availability= re.sub(r'\n+\s+','',book_tags[0].find('p', class_='availability').getText())
availability

'In stock'

In [8]:
#Now, we test a function with the two parameters as filters: `min_rating` and `max_price`.
name_ls=[]

max_price=50
price_ls=[]

rating_dic={'One':1, 'Two':2, 'Three':3, 'Four':4, 'Five':5}
min_rating=3
rating_ls=[]
av_ls=[]

for book in book_tags:
    price= float(book.find('p', class_='price_color').getText().strip('£'))
    
    rating_w=book.find('p', class_='star-rating')['class'][1]
    rating_n=rating_dic[rating_w]
    
    if price <=max_price and rating_n>= min_rating:
        name=book.find('h3').find('a')['title']
        name_ls.append(name)
        price_ls.append(price)
        rating_ls.append(rating_n)
        availability= re.sub(r'\n+\s+','',book.find('p', class_='availability').getText())
        av_ls.append(availability)
        
{'name':name_ls,'p':price_ls,'rating':rating_ls,'availability':av_ls}

{'name': ['Sharp Objects',
  'The Dirty Little Secrets of Getting Your Dream Job',
  'The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull',
  'The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics',
  "Shakespeare's Sonnets",
  'Set Me Free',
  'Rip it Up and Start Again'],
 'p': [47.82, 33.34, 17.93, 22.6, 20.66, 17.46, 35.02],
 'rating': [4, 4, 3, 4, 4, 5, 5],
 'availability': ['In stock',
  'In stock',
  'In stock',
  'In stock',
  'In stock',
  'In stock',
  'In stock']}

In [9]:
#Now is time to start finding the detail pages of each book to gather the other information: description,genre, UPC
#we get the tags which contain the page of a specific book
pages= soup.find('li',class_='current').getText().replace('\n','').strip().split()[3]
print(pages)
#and we read how many pages there might be to extract with books
url='https://books.toscrape.com/catalogue/page-'
type(pages)

50

str

In [21]:
#finding all books within that page
book_tags= soup.find_all('article',class_='product_pod')
basic_url='https://books.toscrape.com/'

b_url= basic_url+book_tags[0].find('h3').find('a')['href']
b_response = requests.get(b_url, headers=headers)
b_soup = BeautifulSoup(b_response.content, 'html.parser')

#finding Genre and description within that page
b_genre= b_soup.find_all('li')[2].getText().replace('\n','')
b_genre
#finding UPC within that page
b_upc= b_soup.find('table', class_='table table-striped').find('th', string='UPC').find_next_sibling('td').text
b_upc
#finding description within that page
b_desc= b_soup.find('div', class_='sub-header').find_next_sibling('p').text
b_desc

"It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special edition. Silverstein's humorous and creative verse can amuse the dowdiest of readers. Lemon-faced adults and fidgety kids sit still and read these rhythmic words and laugh and smile and love th It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special edition. Silverstein's humorous and creative verse can amuse the dowdiest of readers. Lemon-faced adults and fidgety kids sit still and read these rhythmic words and laugh and smile and love that Silverstein. Need proof of his genius? RockabyeRockabye baby, in the treetopDon't you know a treetopIs no safe place to rock?And who put you up there,And your cradle, too?Baby, I think someone down here'sGot it in for you. Shel, you never sounded so good. ...more"

In [26]:
#Now we got all the information, we compile our function in one single code:

import requests
from bs4 import BeautifulSoup
import pandas as pd
import re

def scrape_books(min_rating,max_price):
    url='https://books.toscrape.com/catalogue/page-'
    # Now we identify ourserlves as "humans", and not bots to avoid being blocked.
    headers = {
      "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36"
    }
    
    
    response = requests.get(url+'1.html', headers=headers)
    soup1 = BeautifulSoup(response.content, 'html.parser') #we store the html info in soup with a nice structure
    pages= soup1.find('li',class_='current').getText().replace('\n','').strip().split()[3]
    
    max_price=max_price
    min_rating=min_rating
    
    name_ls=[]
    genre_ls=[]
    price_ls=[]
    rating_ls=[]
    av_ls=[]
    upc_ls=[]
    desc_ls=[]
    
    for page in range(1,int(pages)):  
        url_rel= url+str(page)+'.html'
        response=requests.get(url_rel,headers=headers)
        soup= BeautifulSoup(response.content,'html.parser')
        book_tags= soup.find_all('article',class_='product_pod')
        
        for book in book_tags:
            
            #finding the information of each book
            price= float(book.find('p', class_='price_color').getText().strip('£'))
            
            rating_dic={'One':1, 'Two':2, 'Three':3, 'Four':4, 'Five':5}
            rating_w=book.find('p', class_='star-rating')['class'][1]
            rating_n=rating_dic[rating_w]
        
            if price <=max_price and rating_n>= min_rating:
                name=book.find('h3').find('a')['title'].split(',')[0]
                name_ls.append(name)
                
                price_ls.append(price)
                
                rating_ls.append(rating_n)
                
                availability= re.sub(r'\n+\s+','',book.find('p', class_='availability').getText())
                av_ls.append(availability)
                
                #Going to find detail info from that book
        
                basic_url='https://books.toscrape.com/catalogue/'
                b_url= basic_url+book.find('h3').find('a')['href']
                b_response = requests.get(b_url, headers=headers)
                b_soup = BeautifulSoup(b_response.content, 'html.parser')
        
                #finding Genre and description within that page
                b_genre= b_soup.find_all('li')[2].getText().replace('\n','')
                genre_ls.append(b_genre)
                #finding UPC within that page
                b_upc= b_soup.find('table', class_='table table-striped').find('th', string='UPC').find_next_sibling('td').text
                upc_ls.append(b_upc)
                #finding description within that page
                b_desc= b_soup.find('div', class_='sub-header').find_next_sibling('p').text
                desc_ls.append(b_desc)
    
        
    #creating DataFrame
    df=pd.DataFrame({
            'UPC':upc_ls,
            'Title':name_ls,
            'Price(£)':price_ls,
            'Rating':rating_ls,
            'Genre': genre_ls,
            'Availability':av_ls,
            'Description':desc_ls
        })
    return df

In [27]:
min_rating=4
max_price=30
scrape_books(min_rating,max_price)

,UPC,Title,Price(£),Rating,Genre,Availability,Description
0,e10e1e165dc8be4a,The Boys in the Boat: Nine Americans and Their...,22.60,4,Default,In stock,For readers of Laura Hillenbrand's Seabiscuit ...
1,30a7f60cd76ca58c,Shakespeare's Sonnets,20.66,4,Poetry,In stock,This book is an important and complete collect...
2,ce6396b0f23f6ecc,Set Me Free,17.46,5,Young Adult,In stock,Aaron Ledbetter’s future had been planned out ...
3,c2e46a2ee3b4a322,Chase Me (Paris Nights #2),25.27,5,Romance,In stock,"A Michelin two-star chef at twenty-eight, Viol..."
4,6258a1f6a6dcfe50,The Four Agreements: A Practical Guide to Pers...,17.66,5,Spirituality,In stock,"In The Four Agreements, don Miguel Ruiz reveal..."
...,...,...,...,...,...,...,...
137,4280ac3eab57aa5d,The Girl You Lost,12.29,5,Mystery,In stock,Eighteen years ago your baby daughter was snat...
138,29fc016c459aeb14,The Edge of Reason (Bridget Jones #2),19.18,4,Womens Fiction,In stock,Monday 27 January“7:15 a.m. Hurrah! The wilder...
139,229cd6564bf0dce4,Shadow Rites (Jane Yellowrock #10),21.72,4,Fantasy,In stock,Slaying vampires is child’s play for skinwalke...
140,bcbcbcf0f6ed196f,Paper Girls,21.71,4,Sequential Art,In stock,"In the early hours after Halloween of 1988, fo..."
141,d510567580c8be52,Lost Among the Living,27.70,4,Historical Fiction,In stock,"England, 1921. Three years after her husband, ..."

In [28]:
min_rating=5
max_price=44
scrape_books(min_rating,max_price)

,UPC,Title,Price(£),Rating,Genre,Availability,Description
0,ce6396b0f23f6ecc,Set Me Free,17.46,5,Young Adult,In stock,Aaron Ledbetter’s future had been planned out ...
1,a34ba96d4081e6a4,Rip it Up and Start Again,35.02,5,Music,In stock,"Punk's raw power rejuvenated rock, but by the ..."
2,c2e46a2ee3b4a322,Chase Me (Paris Nights #2),25.27,5,Romance,In stock,"A Michelin two-star chef at twenty-eight, Viol..."
3,00bfed9e18bb36f3,Black Dust,34.53,5,Romance,In stock,"No matter how busy he keeps himself, successfu..."
4,4c28def39d850cdf,Worlds Elsewhere: Journeys Around Shakespeare’...,40.30,5,Nonfiction,In stock,"Anti-apartheid activist, Bollywood screenwrite..."
...,...,...,...,...,...,...,...
119,fff8a057a40c4a60,The Haters,27.89,5,Young Adult,In stock,"From Jesse Andrews, author of the New York Tim..."
120,4280ac3eab57aa5d,The Girl You Lost,12.29,5,Mystery,In stock,Eighteen years ago your baby daughter was snat...
121,b6f1cfadc4dd79d4,Off Sides (Off #1),39.45,5,New Adult,In stock,“I'm not sure what possessed me to do it. Mayb...
122,8d390a1fc3133d06,Jane Eyre,38.43,5,Default,In stock,Orphaned into the household of her Aunt Reed a...
123,72e6fbf4f6382557,Fruits Basket,40.28,5,Sequential Art,In stock,A family with an ancient curse...And the girl ...